import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class PassengerDetails extends javax.swing.JFrame {

    /**
     * Creates new form PassengerDetails
     */
    public PassengerDetails() {
        initComponents();
        autoID();
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtfn = new javax.swing.JTextField();
        txtln = new javax.swing.JTextField();
        txtnationality = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtCR = new javax.swing.JTextField();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtdob = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Add Passenger Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 550));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Passenger ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(54, 78, 130, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(54, 149, 106, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(54, 199, 106, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nationality");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(54, 249, 106, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(54, 306, 97, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Country of Residency");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(405, 149, 200, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Contact No");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(405, 199, 100, 22);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Date of birth");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(405, 95, 130, 22);

        txtid.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 0, 51));
        txtid.setText("label");
        jPanel1.add(txtid);
        txtid.setBounds(228, 66, 97, 44);
        jPanel1.add(txtfn);
        txtfn.setBounds(228, 149, 112, 24);
        jPanel1.add(txtln);
        txtln.setBounds(228, 199, 112, 24);
        jPanel1.add(txtnationality);
        txtnationality.setBounds(228, 249, 112, 24);
        jPanel1.add(txtemail);
        txtemail.setBounds(622, 249, 112, 24);
        jPanel1.add(txtcontact);
        txtcontact.setBounds(622, 199, 112, 24);
        jPanel1.add(txtCR);
        txtCR.setBounds(622, 149, 112, 24);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        r1.setText("Male");
        jPanel1.add(r1);
        r1.setBounds(204, 306, 69, 23);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        r2.setText("Female");
        jPanel1.add(r2);
        r2.setBounds(285, 306, 77, 23);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(473, 382, 112, 38);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(622, 382, 114, 38);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(405, 249, 100, 22);
        jPanel1.add(txtdob);
        txtdob.setBounds(614, 93, 141, 24);

        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 30, 47, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(36, 24, 880, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String id = txtid.getText();
String firstname = txtfn.getText();
String lastname = txtln.getText();
String nationality = txtnationality.getText();
String Residency =txtCR.getText();
String email = txtemail.getText();
DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
String date = da.format(txtdob.getDate());
String Gender;

if (r1.isSelected()){
    Gender ="Male";
}
else{
    Gender="Female";
}
String contact = txtcontact.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","ar#51477773ar");
             pst = con.prepareStatement("Insert into passenger(id,First_name,Last_name,Nationality,dob,Gender,Contact,Email,Residency)Values(?,?,?,?,?,?,?,?,?)");
             pst.setString(1,id);
             pst.setString(2,firstname);
             pst.setString(3,lastname);
             pst.setString(4,nationality);
             pst.setString(5,date);
             pst.setString(6,Gender);
             pst.setString(7,contact);
             pst.setString(8,email);
             pst.setString(9,Residency);
             pst.executeUpdate();
             
             JOptionPane.showMessageDialog(null , "Passeneger Details Successfully Recorded");
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PassengerDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PassengerDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
 public void autoID() 
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","ar#51477773ar");
            Statement s = con.createStatement();
            ResultSet rs =s.executeQuery("Select MAX(id) from passenger");
            rs.next();
            rs.getString("Max(id)");
            if(rs.getString("Max(id)")== null)
            {
                txtid.setText("PS001");
            }
            else{
                long id =Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id)").length()));
                id++;
                txtid.setText("PS" + String.format("%03d",id));
            }
            rs.close();
            con.close();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PassengerDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PassengerDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField txtCR;
    private javax.swing.JTextField txtcontact;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfn;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtln;
    private javax.swing.JTextField txtnationality;
    // End of variables declaration//GEN-END:variables
}
